### ISSUE TITLE
提前申请测试你的APP

### ISSUE THREAD

**Issue by DragonSuper** [neostudy/neoreads#1]
由于工作原因和生活原因，不能参与你的开发计划
我可以复查你的代码，测试你的APP，打个小杂工
我对诗词没有多大兴趣，仅针对开发这块

**Comment by zhaopuming** [comment]
非常感谢，其实我android、kotlin和go都是现学的，所以进度会比较慢。但会一直坚持下去。期待写出功能以后能得到你的帮助

**Comment by DragonSuper** [comment]
> 非常感谢，其实我android、kotlin和go都是现学的，所以进度会比较慢。但会一直坚持下去。期待写出功能以后能得到你的帮助

ok，我写过两年的android，一年多的go，现在在搞云计算，不怎么开发了，有技术问题，可以问我，但是我不参与代码开发，加油，看好你。
